version: '3.1'

services:
  pg_db:
    build: .
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${USER}
    volumes:
      - ./config_postgres/:/var/lib/postgresql/data
      - ./backup_pg/:/backup/
    ports:
      - ${PG_PORT:-5432}:5432


