version: '3.1'

services:
  pg_db:
    build: .
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${USER}
    volumes:
      - /mnt/0/postgres/:/var/lib/postgresql/data
      - /mnt/0/backup/vvy_backup_pg/:/backup/
    ports:
      - ${POSTGRES_PORT:-5432}:5432


